### ISSUE TITLE
Is it possible to embed DSYM (folder) in my IPA through Devops build?

### ISSUE THREAD

**Issue by wouterst79** [xamarin/xamarin-macios#17807]
### Introduction
App Store Connect reports crashes in my production app that aren't reported through AppCenter. I see the crashes through XCode => Organizer, but the crashes aren't symbolicated. 

I suspect the crashes are related to resource constraints, but I would prefer to see the stack trace before I do a lot of work on a hunch :)

Is it possible to include DSYM in the IPA that is produced through Azure Devops?

### Steps to Reproduce

1. Create an IPA for a Xamarin.iOS app:

```
- task: XamariniOS@2
  inputs:
    solutionFile: '**/*iOS.sln'
    configuration: '$(BuildConfiguration)'
    buildForSimulator: false
    _packageApp: true_
    runNugetRestore: true

- task: CopyFiles@2
  inputs:
    Contents: '**/*.dSYM/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(BuildConfiguration)'
    flattenFolders: false

- task: CopyFiles@2
  inputs:
    Contents: '**/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(BuildConfiguration)'
    flattenFolders: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(BuildConfiguration)'
    ArtifactName: $(BuildConfiguration)
    publishLocation: 'Container'

- task: AppStoreRelease@1
  inputs:
    serviceEndpoint: 'app store'
    appIdentifier: 'xxx'
    appType: 'iOS'
    releaseTrack: 'TestFlight'
    shouldSkipWaitingForProcessing: true
    appSpecificId: 'XXX'
```

2. I'm able to then download the DSYM through Build Artifacts: Run => Job => 
![image](https://user-images.githubusercontent.com/6962440/225414892-a2fa0566-089a-4306-ab94-737f6069f012.png)

I suspect I will be able to symbolicate my crashes through some hoop jumping, but it would be nice if that was done for me by xcode / app store connect instead.

3. App Store connect reports there are not Symbols in the .ipa (and I have confirmed there is no DSym in the ipa):
![image](https://user-images.githubusercontent.com/6962440/225415132-b5be69d3-e386-453c-9629-8eecee2d3620.png)

### Question
Is it possible to configure this build (through Additional Build Arguments?, or some other step) to include DSYM in my ipa?
